<?php

$classifier->train('soundtrack', 'It ain\'t "West Side Story", which is quite possibly the best musical ever made.');
$classifier->train('soundtrack', 'It also ain\'t "Singing in the Rain", which is arguably the best postwar musical made in the Hollywood tradition.
');
$classifier->train('soundtrack', 'The songs are insipid.');
$classifier->train('soundtrack', 'The music is dirge-like and not uplifting.');
$classifier->train('soundtrack', 'Also, the big red flag with the story is that the music simply is not very good.');
$classifier->train('soundtrack', 'The music is insipid and totally forgettable.');
$classifier->train('soundtrack', 'The music was dreary and unmemorable, the story was uneven and made little sense. 
');
$classifier->train('soundtrack', 'Mary Poppins, Sound of Music are terrific. But this?! I wanted to run out after half an hour.');
$classifier->train('soundtrack', 'The music is uninteresting.');
$classifier->train('soundtrack', 'I did like the one song John Legend did.');
$classifier->train('soundtrack', 'The singing is slightly better but not much.');
$classifier->train('soundtrack', 'I find the music of LaLaLand with the exception of its main song rather forgettable, the same with most of the choreography.');
$classifier->train('soundtrack', 'Musicals have always been of my favorite movies.');
$classifier->train('soundtrack', 'It had no memorable songs.');
$classifier->train('soundtrack', 'I\'m sorry but Gosling\'s singing was atrocious.');
$classifier->train('soundtrack', 'Script, directing, acting, cinematography, music were all outstanding.');
$classifier->train('soundtrack', 'The sound design combined with a beautiful music score is outstanding - subtle and moving when creating atmosphere, powerful at times of dramatic conflict.');
$classifier->train('soundtrack', 'I should mention the music as well, which was very, very good.');
$classifier->train('soundtrack', 'The music, sound effects and voice actor/actress amplifies the emotions and guides you from start till end.');
$classifier->train('soundtrack', 'The most notable difference is the tone.');
$classifier->train('soundtrack', 'It is really well made, the visuals are just stunning! and the music is quite good.');
$classifier->train('soundtrack', 'The OST is very beautiful! one thing I hate about seeing this movie is that, I have now high expectations and standards for other movies.');
$classifier->train('soundtrack', 'The music score and direction in this film are key selling points, both beautiful and haunting.');
$classifier->train('soundtrack', 'This movie OST perfectly matches the movie which always moves you.');
$classifier->train('soundtrack', 'I think you will like those melodic OSTs.');
$classifier->train('soundtrack', 'The art and music of this film is amazing too.');
$classifier->train('soundtrack', 'I loved the vocal songs that were featured in the movie.');
$classifier->train('soundtrack', 'The theme songs, background music are just perfect.');
$classifier->train('soundtrack', 'And now I am writing this review I am listening to the English version of the song "Sparkle".');
$classifier->train('soundtrack', 'Music is absolutely lovely.');
$classifier->train('soundtrack', 'Only then I got to know that there is an English version of the movie and English version of songs.');
$classifier->train('soundtrack', 'A song plays every once in a while, and all of them are well-suited to the movie and just sound nice.');
$classifier->train('soundtrack', 'The soundtrack is done by Radwimps, a Japanese alt rock band, that breathes life and emotion into scenes due to their wide range of styles and atmosphere.');
$classifier->train('soundtrack', 'Music: I enjoyed it.');
$classifier->train('soundtrack', 'The song (Zen Zen sense) is beautiful too, I like the music and lyrics too.');
$classifier->train('soundtrack', 'It has the rhythm that perfectly blends with the lighthearted music.');
$classifier->train('soundtrack', 'Interestingly there were a lot of pop songs instead of the more typical choice of instrumentals.');
$classifier->train('soundtrack', 'Music is just perfect.');
$classifier->train('soundtrack', 'It fits all the scenes and especially at the ending, you will have an awesome moment feeling the music.');
$classifier->train('soundtrack', 'I thoroughly enjoyed the soundtrack as well.');
$classifier->train('soundtrack', 'The music was good but not the best soundtrack I\'ve heard and would personally have made a completely original soundtrack for a movie like this.');
$classifier->train('soundtrack', 'Music also helped the movie in lot of scenes.');
$classifier->train('soundtrack', 'The sound track is great and cinematography was good.');
$classifier->train('soundtrack', 'The scenery was beautiful and the soundtrack was great.');
$classifier->train('soundtrack', 'Songs were long and annoying.');
$classifier->train('soundtrack', 'There are some good songs.');
$classifier->train('soundtrack', 'A few new songs were added which were quite boring.');
$classifier->train('soundtrack', 'The songs we all heard before.');
$classifier->train('soundtrack', 'All of the songs are slowed down so much that it\'s hard to care about them and they\'re lacking the booming vocals that made the originals so good.');
$classifier->train('soundtrack', 'The songs suck.');
$classifier->train('soundtrack', 'The songs lack the vocal power of the original ones, failing mostly to inspire or make one tap one\'s feet.');
$classifier->train('soundtrack', 'The reused songs have new arrangements & new lyrics, but with the exception of The Mob Song, the changes are distracting and feel oddly paced.');
$classifier->train('soundtrack', 'There are new songs but they are mostly dull.');
$classifier->train('soundtrack', 'The Beast\'s new song is the best of the bunch, but the emotion doesn\'t seem appropriate for the scene.');
$classifier->train('soundtrack', 'Each song establishes its own unique aesthetic, from Gaston\'s bouncy barroom to Be Our Guest\'s Bollywood esque light-show.');
$classifier->train('soundtrack', 'The music is good but some songs were irrelevant and the movie fails to surprise the viewers and hold on to the seat, even 129 minutes seems​ like ages.');
$classifier->train('soundtrack', 'The music is great,but the animation was weak and at times went overboard with the details.');
$classifier->train('soundtrack', 'Songs...overall they were\'t as bad as certain other \'sequel songs\'.');
$classifier->train('soundtrack', 'It was fun while the movie was on, but within an hour I don\'t think I would have remembered any of the songs or even been able to hum any of the tunes.');
$classifier->train('soundtrack', 'However, none of the new songs were that memorable.');
$classifier->train('soundtrack', 'The songs are even worst, from the already bad amount of songs in the original.');
$classifier->train('soundtrack', 'The new songs are mediocre.');
$classifier->train('soundtrack', 'The score and music is perfect.');
$classifier->train('soundtrack', 'Songs that will be stuck in your mind and you will be humming them and you won\'t even know it.');
$classifier->train('soundtrack', '"Let it Go" is the most overrated song I have EVER heard and I was quite disappointed to hear that it had won the Oscar for Best Original Song.');
$classifier->train('soundtrack', 'The music was beautifully composed and don\'t even get me started on how amazing Donna Murphy, Zachary Levi, and Mandy Moore\'s performances were!');
$classifier->train('soundtrack', 'The music was of an exceptionally poor caliber in this film.');
$classifier->train('soundtrack', 'You will be singing the songs over and over.');
$classifier->train('soundtrack', 'First of all, there is only one song that I think was actually good.');
$classifier->train('soundtrack', 'I could not stop myself from skipping at least a minute from most of the songs.');
$classifier->train('soundtrack', 'The songs are for the most part unremarkable, and some of the musical sequences suffer from not fully committing to dialog or singing.');
$classifier->train('soundtrack', 'The animation and audio quality did not match the songs.');
$classifier->train('soundtrack', 'Songs are what Disney movies are known for, yet the songs in this movie ended up being mediocre at best.');
$classifier->train('soundtrack', 'The music is great, and I left singing it.');
$classifier->train('soundtrack', 'Are the songs particularly inventive or that much different from all the countless other Disney movies?');
$classifier->train('soundtrack', 'Songs are extremely repetitive with one exception of \'Let it go\'.');
$classifier->train('soundtrack', 'I saw the song "Let it go" on Youtube before I saw the actual movie and I was amazed with the animations and the song in general.');
$classifier->train('soundtrack', 'The songs are lazy.');
$classifier->train('soundtrack', 'The music is quite forgettable and bland.');
$classifier->train('soundtrack', 'This song has been overplayed, overpraised and it is overrated.');
$classifier->train('soundtrack', 'The music is quite forgettable and bland.');
$classifier->train('soundtrack', 'The songs were childish.');
$classifier->train('soundtrack', 'Now the musics... they are boring.');
$classifier->train('soundtrack', 'Songs did not further the story-telling in any way.');
$classifier->train('soundtrack', 'The songs are not good.');
$classifier->train('soundtrack', 'The music is forgettable.');
$classifier->train('soundtrack', 'None of the songs were remotely memorable.');
$classifier->train('soundtrack', 'Terrible songs, sounded like they were sung by Idols rejects.');
$classifier->train('soundtrack', 'The songs were amazing, some of my favorite Disney songs.');
$classifier->train('soundtrack', 'I love to sing the songs.');
$classifier->train('soundtrack', 'The music is also very well-done with some catchy songs and a great score by Christophe Beck.');
$classifier->train('soundtrack', 'The movie is sweet with a good music.');
$classifier->train('soundtrack', 'The music is amazing and the lyrics are excellent.');
$classifier->train('soundtrack', 'The songs are just so great and catchy, notably \'first time in forever\', \'love is an open door\' and \'let it go\'.');
$classifier->train('soundtrack', 'In summary, this is a great films for all ages with a brilliant soundtrack.');
$classifier->train('soundtrack', 'The songs are great; my personal favorites were "Let it Go" and "For the First Time in Forever."');
$classifier->train('soundtrack', 'The music of Enchanted is witty and wonderful and the story is full of great humor and has a perfect pacing and structure.');
$classifier->train('soundtrack', 'The music is OK if a little too Broadway for my tastes.');
$classifier->train('soundtrack', 'More specifically, it\'s the songs.');
$classifier->train('soundtrack', 'The musics are good and kinda catchy to the children.');
$classifier->train('soundtrack', 'As for the music, it can\'t get any better than this.');
$classifier->train('soundtrack', 'Music is good especially the background music.');
$classifier->train('soundtrack', 'The songs make my ears bleed.');
$classifier->train('soundtrack', 'Most of the music. "Let It Go" is an epic song, and Olaf\'s song is hilarious!');
$classifier->train('soundtrack', 'You will be singing the songs over and over.');
$classifier->train('soundtrack', 'I could not stop myself from skipping at least a minute from most of the songs.');
$classifier->train('soundtrack', 'The music is Disney at its catchiest, the visuals are picturesque, and the characters are irresistibly charming.');

?>