<?php

$classifier->train('character', 'Patty Jenkins directing, Snyder style slo-mo fight scenes (one of the best I have seen), wonderful acting by Gadot and Chris Pine.');
$classifier->train('character', 'Miss Gadot has done an amazing job here.');
$classifier->train('character', 'She has her style looks and every part of it in a way.');
$classifier->train('character', 'Gal Gadot was excellent in this film.');
$classifier->train('character', 'Chris Pine was also really good in this film, as Steve Trevor.');
$classifier->train('character', 'The villain-ploTwist was amusing.');
$classifier->train('character', 'I enjoyed Emma Stone\'s performance much more.');
$classifier->train('character', 'The two main characters are just not strong enough to carry the movie for more than two hours without help.');
$classifier->train('character', 'Ryan Gosling was stiff and bland (as he is most of the time).');
$classifier->train('character', 'A stone cold performance from Emma and the goose is cooked where Ryan is concerned.');
$classifier->train('character', 'Although the actors where good, the "chemistry" was awkward and boring.');
$classifier->train('character', 'She is so horrible that I will make sure she is not an actress in any film I watch again. I wouldn\'t even see her films on a bet.');
$classifier->train('character', 'Annoying things: the worst is, in my opinion, Emma Stone.');
$classifier->train('character', 'I never understood her "talent".');
$classifier->train('character', 'Her singing & dancing are awful.');
$classifier->train('character', 'Mama Mia was superbly acted and sung and loads of fun.');
$classifier->train('character', 'Music Man or Cabaret it was not.');
$classifier->train('character', 'The sets are beautiful.');
$classifier->train('character', 'Their clothes were ugly too.');
$classifier->train('character', 'Stereotypical characterization of black women.');
$classifier->train('character', 'The best group of actors I\'ve seen in one single film in a long, long time.');
$classifier->train('character', 'Characters are all obvious, and repeat themselves one generation after another.');
$classifier->train('character', 'Yes, it had good acting.');
$classifier->train('character', 'Janelle Monáe is also wonderful as his girlfriend as is Naomie Harris as the boy\'s mother.');
$classifier->train('character', 'The acting will blow you away.');
$classifier->train('character', 'Chiron doesn\'t really learn anything.');
$classifier->train('character', 'Beautifully acted, written, directed.');
$classifier->train('character', 'He was afraid of the truth.');
$classifier->train('character', 'Kudos to the writers/producers and cast/crew for a job well done.');
$classifier->train('character', 'I enjoyed Moonlight because I related heavily to the main character.');
$classifier->train('character', 'Chiron is the character we follow through this journey, and he is played by three actors excellently.');
$classifier->train('character', 'the directing all through out the film is mesmerizing, by Barry Jenkins.');
$classifier->train('character', 'The first problem is avoided by amazing acting.');
$classifier->train('character', 'Rhodes is enormous and ripped but he makes you believe that he is Little grown up, you actually recognise Little in Black, which is so weird.');
$classifier->train('character', 'Harris plays the crack-addict mom, she\'s good.');
$classifier->train('character', 'Ali is the big one everybody is talking about, and yeah, he \'s amazing.');
$classifier->train('character', 'A unique look at the life of a gay black man growing up. ');
$classifier->train('character', 'He is certainly introverted and even lonely, his mother is a crack addict.');
$classifier->train('character', 'Taki has selective memory loss about Mitsuha\'s name, hence the title.');
$classifier->train('character', 'The main characters aren\'t overly interesting in their own right, and few, if any, of the side characters are developed throughout the film.');
$classifier->train('character', 'The characters\' are great.');
$classifier->train('character', 'I can\'t decide who I like more, Mitsuha or Taki.');
$classifier->train('character', 'It turns out that Taki had her body vice versa.');
$classifier->train('character', 'The characters are well developed throughout the film as the viewpoint switches between them in an novel way.');
$classifier->train('character', 'The characters act in realistic ways and say things you\'d expect them to say, all without removing the anime charm entirely.');
$classifier->train('character', 'Mitsusha is your typical country girl with a thirst for a life in the city.');
$classifier->train('character', 'I recently saw it, and I loved it, excellent story, very good characters, definitely deserves to be more popular.');
$classifier->train('character', 'We\'re not so lucky with Taki.');
$classifier->train('character', 'Taki falls in love with Mitsuha.');
$classifier->train('character', 'Ishida is a shell of himself and is depressed.');
$classifier->train('character', 'A boy, Ishida, bullies a hearing impaired girl who grows to dislike herself.');
$classifier->train('character', 'Most of the characters are people that you wouldn\'t want to spend much time with and there is maybe only one scene that could be called funny.');
$classifier->train('character', 'There\'s a lot of characters in the movie which does not explain why they bullied Nishimiya.');
$classifier->train('character', 'he movie is tremendously beautiful , the personalities of the characters are very realistic and well shaped !');
$classifier->train('character', 'She is hair-brained, and scatty, completely adorable and wonderful.');
$classifier->train('character', 'Emilia Clarke is LOU CLARKE! From her crazy outfits in the movie to her charming personality, Clarke has it all.');
$classifier->train('character', 'Both Emilia Clarke and Sam Clafin were excellent.');
$classifier->train('character', 'I loved Emily as Lou and Sam as Will.');
$classifier->train('character', 'Emilia Clark has the most expressive face I have ever seen on camera.');
$classifier->train('character', 'I really enjoyed her character.');
$classifier->train('character', 'She is a silly, eccentric, perpetually happy girl.');
$classifier->train('character', 'Emilia Clarke was perfectly cast for this role.');
$classifier->train('character', 'I also feel he played the part very well.');
$classifier->train('character', 'The house Claflin\'s character lives in looks very nice.');
$classifier->train('character', 'I think Emilia Clarke was born to play her.');
$classifier->train('character', 'I think Sam Claflin was also born to play Will.');
$classifier->train('character', 'The acting truly was brilliant.');
$classifier->train('character', 'It is nice to sometimes be able to empathize with the characters as well.');
$classifier->train('character', 'I have neither seen nor heard of these actors prior to seeing this film.');
$classifier->train('character', 'Clarke\'s eyebrows, she\'d convey no emotional range.');
$classifier->train('character', 'Her eyebrows literally stole every scene they were in.');
$classifier->train('character', 'The 2 main characters have great chemistry and Emilia Clark is simply adorable.');
$classifier->train('character', 'Emilia Clark is an absolute delight! Sam Claflin was perfect.');
$classifier->train('character', 'There is no way any other actress could be cuter than Emelia Clarke.');
$classifier->train('character', 'Emilia and Sam have a good chemistry.');
$classifier->train('character', 'Emilia Clarke is famous for the same reason Sasha Grey is, to put it lightly.');
$classifier->train('character', 'Me Before You was great, but the main attraction was Emilia Clarke she is beautiful.');
$classifier->train('character', 'She is wonderful.');
$classifier->train('character', 'Well done Sam Claflin I didn\'t see a single movement out of character.');
$classifier->train('character', 'The acting, especially from Emilia Clarke, who played Lou, was brilliant.');
$classifier->train('character', 'The romantic and chemistry,between the cast.');
$classifier->train('character', 'Keep it up Emilia Clarke, we love you.');
$classifier->train('character', 'Claflin\'s character Will Traynor is good-looking, rich and still influential.');
$classifier->train('character', 'Her acting is superb in every way.');
$classifier->train('character', 'Her eyebrows are a gift from god.');
$classifier->train('character', 'The young actors were great.');
$classifier->train('character', 'Shailene Woodley and Ansel Elgort both have arrows strongly pointing upwards.');
$classifier->train('character', 'Princess syndrome at it\'s worst.');
$classifier->train('character', 'I loved his quirky personality and despite his problems, still has the ability to keep his witty charm.');
$classifier->train('character', 'The acting was awful in this part too, same goes for the story.');
$classifier->train('character', 'Jamie Dornan and Dakota Johnson have no chemistry.');
$classifier->train('character', 'Dornan\'s acting was so clumsy that it was awkward.');
$classifier->train('character', 'First of all, the romance between Ana and Christian is not interesting or immersive.');
$classifier->train('character', 'The acting was terrible.');
$classifier->train('character', 'I love Emma Watson but in this film she is just playing herself trying to play Belle.');
$classifier->train('character', 'Gaston is the villain.');
$classifier->train('character', 'The Beast is just a misunderstood soul from the beginning despite the prologue telling us otherwise.');
$classifier->train('character', 'Emma Watson is beautiful, but she\'s no Belle.');
$classifier->train('character', 'The only good characters are Gaston and LeFou, mostly because they are fun and played by actors who breathe new life into their original shapes.');
$classifier->train('character', 'Emma Watson plays the same character as she always does, with very little acting effort and very little conviction as Belle.');
$classifier->train('character', 'Emma Watson as Belle was extremely unconvincing from the start to the end.');
$classifier->train('character', 'Interesting young British actress.');
$classifier->train('character', 'Only actor in the movie which performance I enjoyed. ');
$classifier->train('character', 'She was very stiff.');
$classifier->train('character', 'The acting was OK, but it failed to ever "sweep you away" like the animated version did for years.');
$classifier->train('character', 'I don\'t dislike her and I could care less about feminism.');
$classifier->train('character', 'I though McGregor was great as Lumiere and hid his English accent well.');
$classifier->train('character', 'Luke Evans did not make a good Gaston.');
$classifier->train('character', 'He just never looks convincing.');
$classifier->train('character', 'She\'s awful as Belle and her dialogue delivery is cringe inducing.');
$classifier->train('character', 'My favourite character was Gastarn.');
$classifier->train('character', 'Gastons character seemed inconsistent, and monsieur d arque wasn\'t creepy enough.');
$classifier->train('character', 'I like Emma Watson but in this her acting felt forced and I think she was miscast.');
$classifier->train('character', 'I found very little to like in the character development.');
$classifier->train('character', 'She looks like a robot in the movie.');
$classifier->train('character', 'Actors are not able to sing and do not improve the old songs.');
$classifier->train('character', 'Mulan and Shang got married.');
$classifier->train('character', 'The characters and animation are mediocre at times, but it never fails at keeping up with the spark that the first had.');
$classifier->train('character', 'Voice acting isn\'t as good.');
$classifier->train('character', 'Mulan is still strong willed and free thinking.');
$classifier->train('character', 'Character immaturity/stupidity.');
$classifier->train('character', 'Elsa and Anna are annoying, stupid, and take little accountability for their actions.');
$classifier->train('character', 'The lead characters are very likable, with memorable sidekicks.');
$classifier->train('character', 'Anna is the main character of this film, not Elsa.');
$classifier->train('character', 'The characters are so two dimensional.');
$classifier->train('character', 'Anna is just a clumsy princess with a fun and energetic nature.');
$classifier->train('character', 'She is also a beautiful young blond.');
$classifier->train('character', 'The characters, like I said, are all original and very amazing and fantastic and just incredibly well-done and is very spectacular.');
$classifier->train('character', 'Characters were well developed and voice acting is top class.');
$classifier->train('character', 'The character, except for Elsa and Sphen, are either boring or annoying.');
$classifier->train('character', 'She liked her sister "Elsa" so much.');
$classifier->train('character', 'She is beautiful and massively talented.');
$classifier->train('character', 'Characters like her are becoming terribly clichéd, which makes it hard to empathize with Anna.');

?>