<?php 



$classifier->train('story', 'An end strong, violent and full of powerful feelings.');
$classifier->train('story', 'This battle scene is the first that marks the serious tone that carries through the rest of the movie. ');
$classifier->train('story', 'Struggling actress meets struggling jazz pianist.');
$classifier->train('story', 'The story is grotesquely poor and without logic.');
$classifier->train('story', 'She falls in love with him when she first hears him play his music.');
$classifier->train('story', 'One night by happenstance - she stumbles into the club and finds him. ');
$classifier->train('story', 'The story line was a C- poor.');
$classifier->train('story', 'It needed much more substance and quality.');
$classifier->train('story', 'The story line is flat.');
$classifier->train('story', 'The dialog is thin. ');
$classifier->train('story', 'La La Land was the slowest most boring movie I have ever seen. ');
$classifier->train('story', 'Don\'t expect to see anything great. ');
$classifier->train('story', 'What this film does really well that a lot of other superheroes origins fall short on is balancing the light and the dark.');
$classifier->train('story', 'LLL is a movie made from plastic. ');
$classifier->train('story', 'The end is the best.');
$classifier->train('story', 'I do not understand at all.');
$classifier->train('story', 'This is a poor man\'s Woody Allen movie!');
$classifier->train('story', 'Plus, the story is quite boring and very slow. ');
$classifier->train('story', 'Girl meets boy, girl gets boy.');
$classifier->train('story', 'Girl loses boy.');
$classifier->train('story', 'Insipid, uninspiring and totally contrived. ');
$classifier->train('story', 'I really wanted to not only like this movie, but love it.');
$classifier->train('story', 'This film was mostly bad.');
$classifier->train('story', 'This film has no plot. ');
$classifier->train('story', 'The ending is the lowest point for this film. ');
$classifier->train('story', 'The story is too flimsy. ');
$classifier->train('story', 'And to top it all off I didn\'t like the ending.');
$classifier->train('story', 'I love musicals but this was one of the worst movies I have ever seen. ');
$classifier->train('story', 'This movie is about droids and not aliens or the engineers.');
$classifier->train('story', 'He can\'t do jack without a GREAT script');
$classifier->train('story', 'Then they explore planet with no protective gear. ');
$classifier->train('story', 'I found the film tedious and dull. ');
$classifier->train('story', 'The story line is predictable and formulaic. ');
$classifier->train('story', 'This film flairs with originality and a unique style of telling It\'s story. ');
$classifier->train('story', 'The story of MOONLIGHT follows the life of Chiron aka Little. ');
$classifier->train('story', 'There the two young boys have a sexual encounter.');
$classifier->train('story', 'When a child, Chiron lives with his single, crack addict mother Paula in a crime ridden neighborhood in Miami. ');
$classifier->train('story', 'My mother could not believe how boring the movie was. ');
$classifier->train('story', 'I wonder why the protagonist is not also a quadriplegic and deaf. ');
$classifier->train('story', 'Juan berates Paula for smoking crack while Paula rebuffs him for selling it to her. ');
$classifier->train('story', 'After confronting Juan about selling drugs to his own mother, Chiron leaves as Juan hangs his head in shame.');
$classifier->train('story', 'Chiron is subsequently arrested.');
$classifier->train('story', 'Child, teen, adult living in a ghetto in Miami.');
$classifier->train('story', 'story goes no where.');
$classifier->train('story', '"Moonlight" presented how hard can life be when poverty exists. ');
$classifier->train('story', 'He suffered an Odessey of self-discover.');
$classifier->train('story', 'As much as I enjoyed Moonlight, I have to admit I found the ending to be anticlimactic.');
$classifier->train('story', 'Moonlight is the story of Chiron, a black gay man growing up in the streets of Miami. ');
$classifier->train('story', 'But in the most glaring gap of all, the boy\'s gayness is never shown.');
$classifier->train('story', 'This movie is all about MEN love. ');
$classifier->train('story', 'I find this movie so boring. ');
$classifier->train('story', 'Tiamat comet is the source of the disaster which affect to this story.');
$classifier->train('story', 'A journey about growth and resilience in the face of overwhelming odds.');
$classifier->train('story', 'The pacing is a lot faster and intense. ');
$classifier->train('story', 'This film, this story, is extraordinary. ');
$classifier->train('story', 'The animation is stunning and complimentary to this one-of-a-kind tale.');
$classifier->train('story', 'Amazing characters, scenery, city life and town life, story. ');
$classifier->train('story', 'I was so afraid when it\'s going to end.');
$classifier->train('story', 'It really had great storytelling, pacing, characters, and emotions throughout.');
$classifier->train('story', 'Good graphics, excellent story, and you are genuinely happy at the end of the movie.');
$classifier->train('story', 'The story keeps you guessing as it progresses, and that\'s what makes it so magical. ');
$classifier->train('story', 'This movie is absolutely incredible. ');
$classifier->train('story', 'It doesn\'t play too much on emotions, but will make the viewer laugh, smile, and shed a tear.');
$classifier->train('story', 'There are tightly plotted reasons for everything that\'s going on, all of which are revealed in good time.');
$classifier->train('story', 'She spoke for all of us, because we were all bound up as one in that moment. ');
$classifier->train('story', 'The story, too, is a beautiful one. ');
$classifier->train('story', 'This movie has a very strong impact to its viewer.');
$classifier->train('story', 'Prepare to be surprised by its beauty and twisting story.');
$classifier->train('story', 'The plot was original and very interesting. ');
$classifier->train('story', 'The story, the animation, the speech, the suspense and mostly the characters. ');
$classifier->train('story', 'The anime demonstrates the sheer acumen of the human personality. ');
$classifier->train('story', 'It is not entirely a sentimental anime, however beyond any doubt pulls on one\'s heart strings. ');
$classifier->train('story', 'It has a superb soundtrack, amazing animation and an intriguing plot. ');
$classifier->train('story', 'The film mixes serious parts such as the town getting destroyed with light hearted comedy.');
$classifier->train('story', 'The movie isn\'t too terribly hard to understand, but it does require you to think at least a little to fully get it. ');
$classifier->train('story', 'But this movie is one of the most charming, transporting, amazing movies I\'ve ever seen.');
$classifier->train('story', 'Story: Very good;');
$classifier->train('story', 'They were very beautiful too, but the stories were a bit slow and boring.');
$classifier->train('story', '"Your Name" is a love story but it is not a conventional love story.');
$classifier->train('story', 'The story is nice and the change of sequences are perfect. ');
$classifier->train('story', 'The story of two teenagers, one from the rural Japan mountain region and the other one from Tokyo.');
$classifier->train('story', 'The story being with a girl and a boy. ');
$classifier->train('story', 'The story is an incredible sci-fi with a lot of heart. ');
$classifier->train('story', 'The movie has a well thought-out plot, with good characters that are easy to empathise with.');
$classifier->train('story', 'They two are just normal kids.');
$classifier->train('story', 'The dialogue is a cringe-fest, characters are unbelievable and the story is boring. ');
$classifier->train('story', 'It might be hard to get at first but they have an interest transition to make you understand.');
$classifier->train('story', 'It was not what the review or synopsis said it would be.');
$classifier->train('story', 'The movie lets the story be told in such an intricate and interesting manner.');
$classifier->train('story', 'This movie can make you cry. ');
$classifier->train('story', 'First the story is amazing and very emotional and a bit harsh. ');
$classifier->train('story', 'It is a redemption story.');
$classifier->train('story', 'I cant say too much, but the movie is very nice and make me so sad.');
$classifier->train('story', 'There is no cursing or obscenities in this movie worth mentioning.');
$classifier->train('story', 'That is when I burst into tears a lot. ');
$classifier->train('story', 'I like the dialogue its quite charming and the comedy bits work really well');
$classifier->train('story', 'This movie is a tragedy, not a love story.');
$classifier->train('story', 'The end is just amazing.');
$classifier->train('story', 'Employing emotional truth to bring the reader to tears.');
$classifier->train('story', 'This story at its heart is about two people who properly listen to each other, it is something good. ');
$classifier->train('story', 'It makes you smile as well as makes you cry.');
$classifier->train('story', 'I am a sucker for a good love story, especially love that I can relate to. ');
$classifier->train('story', 'The story is completely credible, it can happen any time to anyone.');
$classifier->train('story', 'Film is so boring and this is nothing, it has more than one ending.');
$classifier->train('story', 'The movie is an emotional roller coaster right until the very end, so be prepared.');
$classifier->train('story', 'This movie is not bad, because of the idea for an affair between a rich businessman and a normal girl.');
$classifier->train('story', 'This was a terrible movie.');
$classifier->train('story', 'The story line is very stupid.');
$classifier->train('story', 'This movie just SING and SING!! ');
$classifier->train('story', 'Storytelling-wise, it was all over the place. ');
$classifier->train('story', 'This movie is a bit of a disappointment.');
$classifier->train('story', 'Oh I\'m so angry, they ruined my childhood movie. ');
$classifier->train('story', 'The story it portrays, the music and magic and morals knowing that love heals all, unfortunately, I only saw and felt all that from the animated version and not this one.');
$classifier->train('story', 'Mulan II was terrible because of the ending. ');
$classifier->train('story', 'The ending, too easy.');
$classifier->train('story', 'This is an affecting human story, one that is significant. ');
$classifier->train('story', 'The story was inconsistent. ');
$classifier->train('story', 'The overall story is an interesting one, but the execution is rather sloppy and the narrative meanders a bit too much. ');
$classifier->train('story', 'Music and awesome sisterhood story separate this from many animation offerings of the past. ');
$classifier->train('story', 'The story is magical. ');
$classifier->train('story', 'A story of two young sisters.');


?>